server:
  port: 8080

spring:
  application:
    name: JerseyShop
  datasource:
    url: "jdbc:mysql://localhost:3308/jersey-shop"
    driver: "com.mysql.cj.jdbc.Driver"
    username: root
    password: buicuong2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

jwt:
  signerKey: ${JWT_SIGNER_KEY}
